/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.jcdecaux.recruiting.developpers.service.rest;


import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-27T21:07:20.470+01:00")

@Api(value = "attributelangage2developpeur", description = "the attributelangage2developpeur API")
public interface Attributelangage2developpeurApi {

    @ApiOperation(value = "associer un langage de programmation à un développeur,", notes = "", response = Void.class, tags={ "langage", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Void.class) })
    
    @RequestMapping(value = "/attributelangage2developpeur/{langageName}/{userName}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Void> putLangageToDeveloppeur(@ApiParam(value = "The name that needs to be fetched. Use Langage for testing. ",required=true ) @PathVariable("langageName") String langageName,@ApiParam(value = "The name that needs to be fetched. Use Developpeur for testing. ",required=true ) @PathVariable("userName") String userName) {
        // do some magic!
        return new ResponseEntity<Void>(HttpStatus.OK);
    }

}
